services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  # post-microservice:
  #   image: ${DOCKER_REGISTRY-}post-microservice:v1
  #   build:
  #     context: .
  #     dockerfile: src/microservices/PostMicroservice/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80;https://+:443
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=letoangt
  #     - ConnectionStrings__PostMicroserviceDB=Host=postgres;Port=5432;Username=postgres;Password=postgrespw;Database=PostMicroserviceDB
  #   ports:
  #     - 5001:80
  #     - 7001:443
  #   volumes:
  #     - ${USERPROFILE}/.aspnet/https:/https/:ro
  #   depends_on:
  #     - postgres
  #   networks:
  #     - microservices-network

  # comment-microservice:
  #   image: ${DOCKER_REGISTRY-}comment-microservice:v1
  #   build:
  #     context: .
  #     dockerfile: src/microservices/CommentMicroservice/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80;https://+:443
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=letoangt
  #     - ConnectionStrings__CommentMicroserviceDB=Host=postgres;Port=5432;Username=postgres;Password=postgrespw;Database=CommentMicroserviceDB
  #   ports:
  #     - 5002:80
  #     - 7002:443
  #   volumes:
  #     - ${USERPROFILE}/.aspnet/https:/https/:ro
  #   depends_on:
  #     - postgres
  #   networks:
  #     - microservices-network


  # interaction-microservice:
  #   image: ${DOCKER_REGISTRY-}interaction-microservice:v1
  #   build:
  #     context: .
  #     dockerfile: src/microservices/InteractionMicroservice/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80;https://+:443
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=letoangt
  #     - ConnectionStrings__InteractionMicroserviceDB=Host=postgres;Port=5432;Username=postgres;Password=postgrespw;Database=InteractionMicroserviceDB
  #   ports:
  #     - 5003:80
  #     - 7003:443
  #   volumes:
  #     - ${USERPROFILE}/.aspnet/https:/https/:ro
  #   depends_on:
  #     - postgres

# networks:
#   microservices-network:
#     driver: bridge