services:
  # databases
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
      
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  # identity-service:
  #   image: ${DOCKER_REGISTRY-}identity-service:v1
  #   build:
  #     context: ./Discussify.IdentityService
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #     - ConnectionStrings__IdentityServiceDB=Host=postgres;Port=5432;Username=postgres;Password=postgrespw;Database=IdentityServiceDB
  #   volumes:
  #     - ./Discussify.IdentityService:/src/Discussify.IdentityService
  #   depends_on:
  #     - postgres

  # post-service:
  #   image: ${DOCKER_REGISTRY-}post-service:v1
  #   build:
  #     context: ./Discussify.PostService
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5001:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #     - ConnectionStrings__PostServiceDB=Host=postgres;Port=5432;Username=postgres;Password=postgrespw;Database=PostServiceDB
  #   volumes:
  #     - ./Discussify.PostService:/src/Discussify.PostService
  #   depends_on:
  #     - postgres
      
  # comment-service:
  #   image: ${DOCKER_REGISTRY-}comment-service:v1
  #   build:
  #     context: ./Discussify.CommentService
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5002:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #     - ConnectionStrings__CommentServiceDB=Host=postgres;Port=5432;Username=postgres;Password=postgrespw;Database=CommentServiceDB
  #   volumes:
  #     - ./Discussify.CommentService:/src/Discussify.CommentService
  #   depends_on:
  #     - postgres
            
  # interaction-service:
  #   image: ${DOCKER_REGISTRY-}interaction-service:v1
  #   build:
  #     context: ./Discussify.InteractionService
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5003:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #     - ConnectionStrings__InteractionServiceDB=Host=postgres;Port=5432;Username=postgres;Password=postgrespw;Database=InteractionServiceDB
  #   volumes:
  #     - ./Discussify.CommentService:/src/Discussify.CommentService
  #   depends_on:
  #     - postgres