syntax = "proto3";

option csharp_namespace = "InteractionMicroservice.Grpc";

service InteractionService {
    rpc GetInteractionByPostId (GetInteractionByPostIdRequest) returns (GetInteractionByPostIdResponse);
    rpc GetInteractionsByCommentIds (GetInteractionsByCommentIdsRequest) returns (GetInteractionsByCommentIdsResponse);
}

// request model
message GetInteractionByPostIdRequest {
    int32 postId = 1;
}

message GetInteractionsByCommentIdsRequest {
    int32 postId = 1;
    repeated int32 commentIds = 2;
}

// response model
message PostInteractionCount {
    int32 postId = 1;
    int32 upvote = 2;
    int32 downvote = 3;
    int32 comment = 4;
}

message CommentInteractionCount {
    int32 postId = 1;
    int32 commentId = 2;
    int32 upvote = 3;
    int32 downvote = 4;
    int32 comment = 5;
}

message GetInteractionByPostIdResponse {
    PostInteractionCount interactionCount = 1;
}

message GetInteractionsByCommentIdsResponse {
    repeated CommentInteractionCount interactionCounts = 1;
}
